// Shape of the JSON returned by
// GET /api/v1/ai/instances/{idOrAlias} on management-service.
// Mirrors `platform/management-service/fleets.go` GetInstance.

export type Modality = 'text' | 'text+image' | 'text+image+audio' | string;

export interface AvailableModel {
    name: string;
    label?: string;
    digest: string;
    modality: Modality;
    loaded: boolean;
    loadable: boolean;
    /**
     * Estimated cold-load time in seconds (weights mmap + vLLM warm-up
     * + first compile pass). Surfaced by the management service from
     * the fleet's `available_models` JSON. The chat UI uses it to
     * render an honest ETA on the "Model is loading…" notice and to
     * size the polling deadline. Absent → fallback generic message.
     */
    load_time_seconds?: number;
}

export interface InstanceAuth {
    required: boolean;
    issuer: string;
}

/**
 * Sealed-transport (session-relay) descriptor returned by
 * `GET /api/v1/ai/instances/{idOrAlias}`. Tells the chat UI whether the
 * instance speaks the wallet-attested CBOR-AES-GCM protocol so the SDK
 * can negotiate a sealed session against `app_host`.
 */
export interface InstanceSessionRelay {
    enabled: boolean;
    /** Hostname (no scheme) for `/__privasys/session-bootstrap`. */
    app_host: string;
}

export interface Instance {
    id: string;
    alias: string | null;
    fleet_id: string;
    endpoint: string;
    multi_model: boolean;
    loaded_model: AvailableModel | null;
    available_models: AvailableModel[];
    auth: InstanceAuth;
    attestation_server: string;
    /**
     * Path on the management-service that returns this instance's RA-TLS
     * attestation result (e.g. `/api/v1/apps/<id>/attest`). The chat UI
     * resolves it against `NEXT_PUBLIC_API_BASE_URL`. Empty when no app
     * is currently deployed on the fleet.
     */
    attest_url?: string;
    /** Sealed-transport bootstrap descriptor. Absent when disabled. */
    session_relay?: InstanceSessionRelay;
    /** AI tools advertised to this fleet by management-service.
     *  Each entry corresponds to one MCP server reachable from the
     *  confidential-ai container. Empty when no tools are configured. */
    available_tools?: AvailableTool[];
    /** Fleet governance for user-added tools: 'locked' | 'enclave_only' |
     *  'open'. Absent on older deployments → treat as 'locked'. */
    tool_policy?: 'locked' | 'enclave_only' | 'open' | string;
}

/**
 * Public, end-user-facing description of an MCP tool server. Mirrors
 * `PublicTool` in `platform/management-service/ai_tools.go`.
 */
export interface AvailableTool {
    /** Stable machine name, e.g. `lightpanda`. */
    name: string;
    /** Display label, e.g. "Browse links with LightPanda". */
    label: string;
    description?: string;
    icon?: string;
    /** When true, the chat UI must show a confirmation modal before
     *  forwarding any tool call generated by this server. */
    requires_user_confirmation?: boolean;
    /** When true, the user-facing toggle is on by default. */
    enabled_default?: boolean;
    /** Expected sha256 hex of the MCP server's RA-TLS APP_CODE_HASH
     *  extension, used for the green-badge match in the security view. */
    expected_digest?: string;
    /** Optional management-service /attest proxy URL for this server. */
    attest_url?: string;
}
